### ISSUE TITLE
Reason for _raw and _json on Profile?

### ISSUE THREAD

**Issue by dbouwman** [DavidSpriggs/passport-arcgis#1]
First off - thanks for putting this project out there! Thought I'd have to write this, but did a quick search, and boom there it was :)

Quick question though - I'm using this with MEANJS, and thus storing the profile in mongo. In the strategy.js file you are normalizing the profile, which is super helpful, but I was wondering why you attach _raw and _json properties, as they really bloat the object size

These are the lines...
https://github.com/DavidSpriggs/passport-arcgis/blob/master/lib/passport-arcgis/strategy.js#L102-L103

Not having dug through the details of passport or your projects that rely on this, I'm not sure if these properties are anything other than debugging helpers... so I just nuked them :)

Be happy to PR my changes back if this is not needed

**Comment by SandroMartis** [comment]
@DavidSpriggs  What do you think about this?

I strongly suggest to revert this back to include the `profile._raw = body;` and `profile._json = json;`
All the other passport strategies are keeping them and if a user needs them he would have to create it's own fork of passport-arcgis.
If a user does not need this data, he can simply delete it before storing it to a DB.

**Comment by dbouwman** [comment]
@SandroMartis sounds good to me :)

**Comment by DavidSpriggs** [comment]
Lets do it...

**Comment by SandroMartis** [comment]
Thanks a lot for merging. Could you push it to npm? Thank you!

**Comment by DavidSpriggs** [comment]
Done.
